/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as SettingsIndexImport } from './routes/settings/index'
import { Route as LoginIndexImport } from './routes/login/index'
import { Route as HabitsIndexImport } from './routes/habits/index'
import { Route as HabitsHabitIdImport } from './routes/habits/$habitId'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const SettingsIndexRoute = SettingsIndexImport.update({
  path: '/settings/',
  getParentRoute: () => rootRoute,
} as any)

const LoginIndexRoute = LoginIndexImport.update({
  path: '/login/',
  getParentRoute: () => rootRoute,
} as any)

const HabitsIndexRoute = HabitsIndexImport.update({
  path: '/habits/',
  getParentRoute: () => rootRoute,
} as any)

const HabitsHabitIdRoute = HabitsHabitIdImport.update({
  path: '/habits/$habitId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/habits/$habitId': {
      id: '/habits/$habitId'
      path: '/habits/$habitId'
      fullPath: '/habits/$habitId'
      preLoaderRoute: typeof HabitsHabitIdImport
      parentRoute: typeof rootRoute
    }
    '/habits/': {
      id: '/habits/'
      path: '/habits'
      fullPath: '/habits'
      preLoaderRoute: typeof HabitsIndexImport
      parentRoute: typeof rootRoute
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginIndexImport
      parentRoute: typeof rootRoute
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  HabitsHabitIdRoute,
  HabitsIndexRoute,
  LoginIndexRoute,
  SettingsIndexRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/habits/$habitId",
        "/habits/",
        "/login/",
        "/settings/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/habits/$habitId": {
      "filePath": "habits/$habitId.tsx"
    },
    "/habits/": {
      "filePath": "habits/index.tsx"
    },
    "/login/": {
      "filePath": "login/index.tsx"
    },
    "/settings/": {
      "filePath": "settings/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
